blank_issues_enabled: true
contact_links:
  - name: Esports Pick'em Discord Bot Documentation
    url: https://github.com/wxboysuper/Esports-Pickem-Discord-Bot/docs
    about: Check out the documentation before creating an issue.
