"""Add Team model and leaguepedia_ids

Revision ID: 013252c0b7c1
Revises: 71de3e2a6c09
Create Date: 2025-10-12 21:18:26.096159

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '013252c0b7c1'
down_revision = '71de3e2a6c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('leaguepedia_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roster', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_leaguepedia_id'), 'team', ['leaguepedia_id'], unique=True)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=True)
    op.add_column('contest', sa.Column('leaguepedia_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_contest_leaguepedia_id'), 'contest', ['leaguepedia_id'], unique=True)
    op.add_column('match', sa.Column('leaguepedia_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_match_leaguepedia_id'), 'match', ['leaguepedia_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_leaguepedia_id'), table_name='match')
    op.drop_column('match', 'leaguepedia_id')
    op.drop_index(op.f('ix_contest_leaguepedia_id'), table_name='contest')
    op.drop_column('contest', 'leaguepedia_id')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_leaguepedia_id'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###