"""Add status and score to Pick model

Revision ID: 0bbed2fbcb3f
Revises: 001
Create Date: 2025-10-09 04:20:39.933618

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0bbed2fbcb3f'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pick', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pick', sa.Column('score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pick_status'), 'pick', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pick_status'), table_name='pick')
    op.drop_column('pick', 'score')
    op.drop_column('pick', 'status')
    # ### end Alembic commands ###