"""Make leaguepedia_ids non-nullable

Revision ID: 297e39491342
Revises: 013252c0b7c1
Create Date: 2025-10-12 21:27:38.637843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297e39491342'
down_revision = '013252c0b7c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('leaguepedia_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('leaguepedia_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('leaguepedia_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('leaguepedia_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###