"""Add is_correct to Pick model

Revision ID: 49d418eef62a
Revises: f0d70cdc3b5a
Create Date: 2025-12-25 14:18:33.158435

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "49d418eef62a"
down_revision = "f0d70cdc3b5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("pick")]

    if "is_correct" not in columns:
        op.add_column(
            "pick", sa.Column("is_correct", sa.Boolean(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("pick")]

    if "is_correct" in columns:
        op.drop_column("pick", "is_correct")
    # ### end Alembic commands ###
