"""add best_of to match

Revision ID: 5189ee0b10d0
Revises: 578d2e46a72d
Create Date: 2025-10-14 14:02:29.536037

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5189ee0b10d0"
down_revision = "578d2e46a72d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("match")]
    if "best_of" not in columns:
        op.add_column("match", sa.Column("best_of", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "best_of")
    # ### end Alembic commands ###
