"""initial_migration

Revision ID: 71de3e2a6c09
Revises:
Create Date: 2025-10-12 20:07:04.548276

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from src import models as src_models


# revision identifiers, used by Alembic.
revision = '71de3e2a6c09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', src_models.TZDateTime(length=64), nullable=False),
    sa.Column('end_date', src_models.TZDateTime(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_name'), 'contest', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_discord_id'), 'user', ['discord_id'], unique=True)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('team1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_time', src_models.TZDateTime(length=64), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_contest_id'), 'match', ['contest_id'], unique=False)
    op.create_index(op.f('ix_match_scheduled_time'), 'match', ['scheduled_time'], unique=False)
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('chosen_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('timestamp', src_models.TZDateTime(length=64), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_contest_id'), 'pick', ['contest_id'], unique=False)
    op.create_index(op.f('ix_pick_match_id'), 'pick', ['match_id'], unique=False)
    op.create_index(op.f('ix_pick_status'), 'pick', ['status'], unique=False)
    op.create_index(op.f('ix_pick_user_id'), 'pick', ['user_id'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_index(op.f('ix_pick_user_id'), table_name='pick')
    op.drop_index(op.f('ix_pick_status'), table_name='pick')
    op.drop_index(op.f('ix_pick_match_id'), table_name='pick')
    op.drop_index(op.f('ix_pick_contest_id'), table_name='pick')
    op.drop_table('pick')
    op.drop_index(op.f('ix_match_scheduled_time'), table_name='match')
    op.drop_index(op.f('ix_match_contest_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_user_discord_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_contest_name'), table_name='contest')
    op.drop_table('contest')
    # ### end Alembic commands ###