"""add last_announced_score to match

Revision ID: f0d70cdc3b5a
Revises: 5189ee0b10d0
Create Date: 2025-10-14 14:04:38.056122

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = "f0d70cdc3b5a"
down_revision = "5189ee0b10d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("match")]
    if "last_announced_score" not in columns:
        op.add_column(
            "match",
            sa.Column(
                "last_announced_score",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            ),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "last_announced_score")
    # ### end Alembic commands ###
